import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';
import react from '@vitejs/plugin-react';
import { defineConfig, loadEnv, type Plugin } from 'vite';

const ROOT = __dirname;
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { version: string };
/** vercel.json's page headers (CSP, Permissions-Policy), also served by `vite preview` so screenshots run under the real policy. */
const vercel = JSON.parse(readFileSync(join(ROOT, 'vercel.json'), 'utf8')) as { headers: { source: string; headers: { key: string; value: string }[] }[] };
const PAGE_HEADERS = Object.fromEntries(vercel.headers.find((h) => h.source === '/(.*)')!.headers.map((h) => [h.key, h.value]));

/**
 * The ONNX runtime's WASM and the two models, gzipped once (cached in node_modules/.cache) with a
 * content hash in the name. The app fetches these and unpacks them with DecompressionStream, so the
 * download is small whatever the host does about compression: runtime 14.2 MB -> ~3.7 MB, crop model
 * 4.8 MB -> ~0.2 MB.
 */
interface Packed { key: 'wasm' | 'leaf' | 'crop'; url: string; file: string; bytes: number; raw: number }
function pack(): Packed[] {
  const cacheDir = join(ROOT, 'node_modules', '.cache', 'fs-models');
  mkdirSync(cacheDir, { recursive: true });
  const sources = [
    { key: 'wasm' as const, src: join(ROOT, 'node_modules', 'onnxruntime-web', 'dist', 'ort-wasm-simd-threaded.wasm'), name: 'ort', ext: 'wasm' },
    { key: 'leaf' as const, src: join(ROOT, 'public', 'models', 'leaf.onnx'), name: 'leaf', ext: 'onnx' },
    { key: 'crop' as const, src: join(ROOT, 'public', 'models', 'crop.onnx'), name: 'crop', ext: 'onnx' },
  ];
  return sources.map(({ key, src, name, ext }) => {
    const raw = readFileSync(src);
    const hash = createHash('sha256').update(raw).digest('hex').slice(0, 10);
    const fileName = `${name}.${hash}.${ext}.gz`;
    const file = join(cacheDir, fileName);
    if (!existsSync(file)) writeFileSync(file, gzipSync(raw, { level: 9 }));
    return { key, url: `/models/${fileName}`, file, bytes: statSync(file).size, raw: raw.length };
  });
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((f) => {
    const p = join(dir, f);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const SW = (version: string, shell: string[]) => `// FarmSaathi service worker (generated by vite.config.ts). Version ${version}.
const SHELL = 'fs-shell-${version}';
const MODELS = 'fs-models-v1';
const PRECACHE = ${JSON.stringify(shell)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(SHELL).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('fs-shell-') && k !== SHELL).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // Network first so a new version shows up; the cached shell when there is no signal.
    e.respondWith(fetch(req).catch(() => caches.match('/index.html', { cacheName: SHELL })));
    return;
  }
  if (url.pathname.startsWith('/models/')) {
    e.respondWith(caches.open(MODELS).then((c) => c.match(req).then((hit) => hit || fetch(req))));
    return;
  }
  e.respondWith(caches.match(req, { cacheName: SHELL }).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok && (url.pathname.startsWith('/assets/') || url.pathname.startsWith('/icons/'))) {
      const copy = res.clone();
      caches.open(SHELL).then((c) => c.put(req, copy));
    }
    return res;
  })));
});
`;

function modelAssets(): Plugin {
  const packed = pack();
  let outDir = '';
  return {
    name: 'farmsaathi-models',
    config: () => ({
      define: {
        __MODEL_ASSETS__: JSON.stringify(Object.fromEntries(packed.map((p) => [p.key, { url: p.url, bytes: p.bytes, raw: p.raw }]))),
      },
    }),
    configResolved(c) { outDir = c.build.outDir; },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const hit = packed.find((p) => req.url === p.url);
        if (!hit) return next();
        res.setHeader('Content-Type', 'application/gzip');
        res.setHeader('Content-Length', String(hit.bytes));
        res.end(readFileSync(hit.file));
      });
    },
    generateBundle() {
      for (const p of packed) this.emitFile({ type: 'asset', fileName: p.url.slice(1), source: readFileSync(p.file) });
    },
    writeBundle() {
      const dist = resolve(ROOT, outDir);
      // The raw .onnx copies from public/ and the runtime's own .wasm are never fetched: drop them.
      for (const f of walk(dist)) {
        const rel = relative(dist, f).replace(/\\/g, '/');
        if ((rel.startsWith('models/') && rel.endsWith('.onnx')) || (rel.startsWith('assets/') && rel.endsWith('.wasm'))) rmSync(f);
      }
      const shell = walk(dist)
        .map((f) => '/' + relative(dist, f).replace(/\\/g, '/'))
        .filter((u) => !u.startsWith('/models/') && !u.startsWith('/licenses/') && !u.startsWith('/landing/') && !u.startsWith('/.vite/') && u !== '/sw.js' && u !== '/og.png' && !/\/assets\/(mock|ort|infer)[-.]/.test(u) && !u.endsWith('.map'))
        .sort();
      const version = createHash('sha256').update(shell.join('\n')).update(readFileSync(join(dist, 'index.html'))).digest('hex').slice(0, 10);
      writeFileSync(join(dist, 'sw.js'), SW(version, shell));
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, ROOT, 'VITE_');
  const mock = mode === 'mock' || env.VITE_API === 'mock';
  return {
    plugins: [react(), modelAssets()],
    define: {
      __APP_VERSION__: JSON.stringify(pkg.version),
      __MOCK__: JSON.stringify(mock),
    },
    server: { port: 5176, strictPort: true },
    preview: { port: 5176, strictPort: true, headers: PAGE_HEADERS },
    optimizeDeps: { exclude: ['onnxruntime-web'] },
    build: {
      outDir: mock ? 'dist-mock' : 'dist',
      target: 'es2022',
      manifest: true,
      assetsInlineLimit: 0,
      chunkSizeWarningLimit: 600,
    },
  };
});
